//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.RHS.EnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_distinct
    {
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int zip { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public int ID { get; set; }
    }
}
