//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.RHS.EnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestGrade_view
    {
        public int id { get; set; }
        public int busid { get; set; }
        public Nullable<System.DateTime> latestdate { get; set; }
        public string ins_grade { get; set; }
    }
}
