//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.RHS.EnityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RHSEntities : DbContext
    {
        public RHSEntities()
            : base("name=RHSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<BusinessDetails> BusinessDetails { get; set; }
        public virtual DbSet<Violations> Violations { get; set; }
        public virtual DbSet<Business_distinct> Business_distinct { get; set; }
        public virtual DbSet<Scores> Scores { get; set; }
        public virtual DbSet<Zip_Scores> Zip_Scores { get; set; }
        public virtual DbSet<LatestGrade_view> LatestGrade_view { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<rest_by_CSZ_Result> rest_by_CSZ(Nullable<decimal> lat, Nullable<decimal> lng, string city, string zip, string state, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_by_CSZ_Result>("rest_by_CSZ", latParameter, lngParameter, cityParameter, zipParameter, stateParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<rest_by_dist_Result> rest_by_dist(Nullable<decimal> lat, Nullable<decimal> lng, Nullable<int> distance, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_by_dist_Result>("rest_by_dist", latParameter, lngParameter, distanceParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<rest_by_dist_map_view_Result> rest_by_dist_map_view(Nullable<decimal> lat, Nullable<decimal> lng, Nullable<int> distance, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_by_dist_map_view_Result>("rest_by_dist_map_view", latParameter, lngParameter, distanceParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual int rest_by_dist_NSG(Nullable<decimal> lat, Nullable<decimal> lng, Nullable<int> distance, string name, string rscore, string rgrade, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var rscoreParameter = rscore != null ?
                new ObjectParameter("rscore", rscore) :
                new ObjectParameter("rscore", typeof(string));
    
            var rgradeParameter = rgrade != null ?
                new ObjectParameter("rgrade", rgrade) :
                new ObjectParameter("rgrade", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rest_by_dist_NSG", latParameter, lngParameter, distanceParameter, nameParameter, rscoreParameter, rgradeParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<rest_by_id_Result> rest_by_id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_by_id_Result>("rest_by_id", idParameter);
        }
    
        public virtual ObjectResult<rest_by_name_Result> rest_by_name(Nullable<decimal> lat, Nullable<decimal> lng, string rname, Nullable<int> distance)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var rnameParameter = rname != null ?
                new ObjectParameter("rname", rname) :
                new ObjectParameter("rname", typeof(string));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_by_name_Result>("rest_by_name", latParameter, lngParameter, rnameParameter, distanceParameter);
        }
    
        public virtual int rest_by_name_dist(Nullable<decimal> lat, Nullable<decimal> lng, string rname, Nullable<int> distance)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var rnameParameter = rname != null ?
                new ObjectParameter("rname", rname) :
                new ObjectParameter("rname", typeof(string));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rest_by_name_dist", latParameter, lngParameter, rnameParameter, distanceParameter);
        }
    
        public virtual int rest_by_name_dist_test(Nullable<decimal> lat, Nullable<decimal> lng, string rname, Nullable<int> distance)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            var rnameParameter = rname != null ?
                new ObjectParameter("rname", rname) :
                new ObjectParameter("rname", typeof(string));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rest_by_name_dist_test", latParameter, lngParameter, rnameParameter, distanceParameter);
        }
    
        public virtual ObjectResult<rest_by_zip_Result> rest_by_zip(Nullable<int> distance, Nullable<int> zip)
        {
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            var zipParameter = zip.HasValue ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_by_zip_Result>("rest_by_zip", distanceParameter, zipParameter);
        }
    
        public virtual ObjectResult<rest_map_listing_Result> rest_map_listing(Nullable<int> id, Nullable<decimal> lat, Nullable<decimal> lng)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_map_listing_Result>("rest_map_listing", idParameter, latParameter, lngParameter);
        }
    
        public virtual ObjectResult<rest_name_grade_Result> rest_name_grade(Nullable<int> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rest_name_grade_Result>("rest_name_grade", ridParameter);
        }
    
        public virtual int rest_startid_endid_geol(Nullable<int> sid, Nullable<int> eid, Nullable<decimal> lat, Nullable<decimal> lng)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            var eidParameter = eid.HasValue ?
                new ObjectParameter("eid", eid) :
                new ObjectParameter("eid", typeof(int));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(decimal));
    
            var lngParameter = lng.HasValue ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rest_startid_endid_geol", sidParameter, eidParameter, latParameter, lngParameter);
        }
    
        public virtual ObjectResult<SP_GetAvgScoresByCity_Result> SP_GetAvgScoresByCity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAvgScoresByCity_Result>("SP_GetAvgScoresByCity");
        }
    
        public virtual ObjectResult<SP_GetAvgScoresByRestaurent_Result> SP_GetAvgScoresByRestaurent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAvgScoresByRestaurent_Result>("SP_GetAvgScoresByRestaurent");
        }
    
        public virtual ObjectResult<SP_GetScores_Result> SP_GetScores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetScores_Result>("SP_GetScores");
        }
    
        public virtual ObjectResult<SP_GetScoresByZip_Result> SP_GetScoresByZip()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetScoresByZip_Result>("SP_GetScoresByZip");
        }
    
        public virtual int test(string tname)
        {
            var tnameParameter = tname != null ?
                new ObjectParameter("tname", tname) :
                new ObjectParameter("tname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("test", tnameParameter);
        }
    
        public virtual int test2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("test2");
        }
    }
}
