//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.RHS.EnityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violations
    {
        public int id { get; set; }
        public string violation_number { get; set; }
        public string violations_description { get; set; }
        public Nullable<int> occurrences { get; set; }
        public Nullable<int> bus_id { get; set; }
    
        public virtual BusinessDetails BusinessDetails { get; set; }
    }
}
